#!/usr/bin/env python3
"""
gen_custom_items_sql.py — generate custom_items.sql from custom_items_reference.lua

Reads the hand-wired MimicXI custom-item design reference (211 items, IDs
29700-29910) and emits INSERT rows for item_basic / item_equipment /
item_weapon / item_mods into a single SQL file.

The 29700-29910 range does NOT overlap any stock LSB item, so the output file
opens with a DELETE of that exact range and is fully idempotent. List it in
modules/init.txt so dbtool applies it AFTER the stock item_*.sql, and the
custom items (and their mods) survive every `dbtool update`.

Usage:
    python tools/gen_custom_items_sql.py \
        --ref "G:/Games/FFXI/ShiningFantasia/custom_mimic_items/custom_items_reference.lua" \
        --out modules/custom/custom_items/sql/custom_items.sql
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ID_LO, ID_HI = 29700, 29910

# reference type -> LSB item_basic.type
LSB_TYPE = {4: 6, 5: 7}  # 4=armor -> EQUIPMENT_TYPE(6), 5=weapon -> WEAPON_TYPE(7)

# reference flags -> LSB item_basic.flags
#   0x0000 regular drop  : CANEQUIP | NOSALE | NODELIVERY            (tradeable, no AH)
#   0x0C00 NM drop        : + NOAUCTION | EX | RARE                   (== 63552, matches
#                                                                      the old armor2.json customs)
FLAG_CANEQUIP, FLAG_NOSALE, FLAG_NODELIVERY = 2048, 4096, 8192
FLAG_NOAUCTION, FLAG_EX, FLAG_RARE = 64, 16384, 32768
FLAGS_REGULAR = FLAG_CANEQUIP | FLAG_NOSALE | FLAG_NODELIVERY            # 14336
FLAGS_NM      = FLAGS_REGULAR | FLAG_NOAUCTION | FLAG_EX | FLAG_RARE     # 63552

# String mod-id placeholders in the reference, resolved against
# scripts/enum/mod.codegen.lua (post-base-sync enum).
STRING_MOD = {
    "FASTCAST":                  170,   # FASTCAST
    "MOVE_SPEED":                76,    # MOVE_SPEED_GEAR_BONUS
    "PHALANX_BONUS":             301,   # PHALANX
    "WIND_ELE_ACC":              42,    # WIND_MACC
    "DIVINE_SKILL":              111,   # DIVINE (Divine Magic skill)
    "MAG_DMG_TAKEN":             163,   # DMGMAGIC  (value stays negative %)
    "REFRESH_MOD":               369,   # REFRESH
    "SINGING_SKILL":             119,   # SINGING
    "SHIELD_SKILL":              109,   # SHIELD
    "BLU_SKILL":                 122,   # BLUE (Blue Magic skill)
    "SPELL_INTERRUPT_RATE_DOWN": 168,   # SPELLINTERRUPT
    "REGAIN":                    368,   # REGAIN
    # PET_HP (Automaton HP+100 on 29910) has no clean flat item-mod in LSB.
    # Left unresolved on purpose -> emitted as a TODO comment, no row.
    "PET_HP":                    None,
}

ENTRY_RE = re.compile(r"\{id=\d+.*?mods=\{.*?\}\s*\}\s*\}", re.S)
KV_RE = re.compile(r'(\w+)=("(?:[^"\\]|\\.)*"|0x[0-9A-Fa-f]+|-?\d+)')
MOD_ITEM_RE = re.compile(r'\{\s*("(?:[^"\\]|\\.)*"|-?\d+)\s*,\s*(-?\d+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}')


def _num(tok: str) -> int:
    return int(tok, 16) if tok.lower().startswith("0x") else int(tok)


def parse_entries(text: str) -> list[dict]:
    # Only the customItems = { ... } body; everything before it is the comment legend.
    body = text.split("local customItems", 1)[-1]
    out = []
    for m in ENTRY_RE.finditer(body):
        chunk = m.group(0)
        fields: dict[str, object] = {}
        for kv in KV_RE.finditer(chunk.split("mods=", 1)[0]):
            k, v = kv.group(1), kv.group(2)
            if v.startswith('"'):
                fields[k] = v[1:-1]
            else:
                fields[k] = _num(v)
        mods_part = chunk.split("mods=", 1)[1] if "mods=" in chunk else ""
        mods = []
        for mi in MOD_ITEM_RE.finditer(mods_part):
            mid_tok, val, desc = mi.group(1), int(mi.group(2)), mi.group(3)
            if mid_tok.startswith('"'):
                mods.append(("str", mid_tok[1:-1], val, desc))
            else:
                mods.append(("num", int(mid_tok), val, desc))
        fields["_mods"] = mods
        out.append(fields)
    return out


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def build_sql(entries: list[dict]) -> str:
    L: list[str] = []
    w = L.append
    w("-- ============================================================================")
    w("-- MimicXI custom items (IDs {}-{}) — GENERATED by tools/gen_custom_items_sql.py".format(ID_LO, ID_HI))
    w("-- Source: ShiningFantasia/custom_mimic_items/custom_items_reference.lua")
    w("-- Do not hand-edit. Regenerate after changing the reference.")
    w("-- This range never overlaps stock LSB items; list this file in modules/init.txt")
    w("-- so dbtool applies it after sql/item_*.sql.")
    w("-- ============================================================================")
    w("")
    for t in ("item_mods", "item_weapon", "item_equipment", "item_basic"):
        w(f"DELETE FROM `{t}` WHERE `itemId` BETWEEN {ID_LO} AND {ID_HI};")
    # item_basic uses `itemid` (lower d)
    w(f"DELETE FROM `item_basic` WHERE `itemid` BETWEEN {ID_LO} AND {ID_HI};")
    w("")

    todo: list[str] = []
    seen: set[int] = set()

    for e in sorted(entries, key=lambda x: x["id"]):
        iid = int(e["id"])
        if not (ID_LO <= iid <= ID_HI):
            todo.append(f"-- SKIPPED {iid} {e.get('name')}: id outside {ID_LO}-{ID_HI}")
            continue
        if iid in seen:
            todo.append(f"-- DUPLICATE id {iid} ({e.get('name')}) — later entry ignored")
            continue
        seen.add(iid)

        name = e["name"]
        rtype = int(e["type"])
        lsb_type = LSB_TYPE.get(rtype, 6)
        flags = FLAGS_NM if int(e.get("flags", 0)) else FLAGS_REGULAR
        is_weapon = rtype == 5

        w(f"-- {iid}  {e.get('displayName', name)}  ({e.get('source', '')})")
        w(
            "INSERT INTO `item_basic` "
            "(`itemid`,`subid`,`name`,`sortname`,`name_jp`,`type`,`stackSize`,`flags`,`aH`,`BaseSell`) VALUES "
            f"({iid}, 0, '{esc(name)}', '{esc(name)}', '', {lsb_type}, 1, {flags}, 0, 0);"
        )

        level = int(e.get("level", 1))
        jobs = int(e.get("jobs", 0))
        slot = int(e.get("slot", 0))
        mid = int(e.get("model", 0))
        w(
            "INSERT INTO `item_equipment` "
            "(`itemId`,`name`,`level`,`ilevel`,`jobs`,`MId`,`shieldSize`,`scriptType`,`slot`,`rslot`,`rslotlook`,`su_level`) VALUES "
            f"({iid}, '{esc(name)}', {level}, 0, {jobs}, {mid}, 0, 0, {slot}, 0, 0, 0);"
        )

        if is_weapon:
            w(
                "INSERT INTO `item_weapon` "
                "(`itemId`,`name`,`skill`,`subskill`,`ilvl_skill`,`ilvl_parry`,`ilvl_macc`,`dmgType`,`hit`,`delay`,`dmg`,`unlock_points`) VALUES "
                f"({iid}, '{esc(name)}', {int(e.get('weaponSkill', 0))}, 0, 0, 0, 0, "
                f"{int(e.get('dmgType', 0))}, 1, {int(e.get('delay', 0))}, {int(e.get('dmg', 0))}, 0);"
            )

        rows: list[tuple[int, int]] = []
        if not is_weapon and int(e.get("def", 0)) != 0:
            rows.append((1, int(e["def"])))  # mod 1 = DEF
        for kind, mid_or_name, val, desc in e["_mods"]:
            if kind == "num":
                rows.append((int(mid_or_name), val))
            else:
                resolved = STRING_MOD.get(mid_or_name, "MISSING")
                if resolved is None:
                    w(f"-- TODO {iid}: mod '{mid_or_name}' ({desc}) has no LSB id yet — row omitted")
                    todo.append(f"-- {iid}: unresolved mod '{mid_or_name}' ({desc})")
                    continue
                if resolved == "MISSING":
                    w(f"-- TODO {iid}: mod string '{mid_or_name}' ({desc}) not in STRING_MOD map")
                    todo.append(f"-- {iid}: unmapped mod string '{mid_or_name}' ({desc})")
                    continue
                rows.append((int(resolved), val))

        # de-dupe (itemId, modId) — item_mods PK is (itemId, modId); sum collisions
        agg: dict[int, int] = {}
        for mid_, v in rows:
            agg[mid_] = agg.get(mid_, 0) + v
        for mid_, v in sorted(agg.items()):
            w(f"INSERT INTO `item_mods` VALUES ({iid}, {mid_}, {v});")
        w("")

    if todo:
        w("-- ----------------------------------------------------------------------------")
        w("-- Generator notes:")
        for line in todo:
            w(line)

    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ref", required=True, help="path to custom_items_reference.lua")
    ap.add_argument("--out", required=True, help="output .sql path")
    args = ap.parse_args()

    ref = Path(args.ref)
    text = ref.read_text(encoding="utf-8")
    entries = parse_entries(text)
    if not entries:
        print("ERROR: parsed 0 entries — check the reference file format", file=sys.stderr)
        return 1

    sql = build_sql(entries)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql, encoding="utf-8")

    weapons = sum(1 for e in entries if int(e["type"]) == 5)
    armor = len(entries) - weapons
    modrows = sql.count("INSERT INTO `item_mods`")
    print(f"parsed {len(entries)} entries ({armor} armor, {weapons} weapon)")
    print(f"wrote {out}  ({modrows} item_mods rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
